language: python
python:
  - "3.9"
#  - "3.7"
install: "pip install -r requirements.txt"
script: 
  - py.test --cov --cov-report=xml owm tests -vv
  - sonar-scanner
after_success:
  - coveralls
addons:
  sonarcloud:
    organization: jwoytek
